version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1 # Invoke the Heroku orb

jobs:
  deploy:
    docker:
      - image: registry.heroku.com/docker-hy-pipeline/web
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: git push https://git.heroku.com/docker-hy-pipeline.git


