# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  docker: circleci/docker@1.0.0
workflows:
  deploy:
    jobs:
      - docker/publish:
          image: yves6000/docker-hy.github.io
          tag: 'latest'